### ISSUE TITLE
How to access model checkpoints without safetensor. I want to load the model in PyTorch Lightning

### ISSUE THREAD

**Issue by aniketmaurya** [Stability-AI/generative-models#74]

**Comment by FurkanGozukara** [comment]
diffuser files are already there

https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main

you can watch my this tutorial to see how my custom gradio loads 

[**Stable Diffusion XL (SDXL) Locally On Your PC - 8GB VRAM - Easy Tutorial With Automatic Installer**](https://youtu.be/__7VNmnn5iU)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/3UAi7i7oLdtvlibSlx4z9.png)](https://youtu.be/__7VNmnn5iU)

**Comment by jenuk** [comment]
There will be no distribution of non-safetensors files. However, that is not a problem, safetensors contain all important information and you can load safetensors easily into a pytorch lightning module, see for example our code here:

https://github.com/Stability-AI/generative-models/blob/45c443b316737a4ab6e40413d7794a7f5657c19f/sgm/models/diffusion.py#L85-L103

If you really need the older pytorch-based format, I would recommend that you convert the weights yourself, since it is not safe to open these files from other persons.
